### ISSUE TITLE
Compass and activator not shown

### ISSUE THREAD

**Issue by erayalakese** [Rseding91/Alien-Oil#1]
Hello,

I've enabled the mod but I don't get something. here is no activator, compass or oil spout in me crafting screen (which opens with E key) . These elements shown at crafting screen only once and then disappeared immediately. What's I'm missing?

**Comment by Rseding91** [comment]
The compass is unlocked with alien technology research. The activator is found in the wild (or through using the compass) and the spouts are created using the activator.

**Comment by erayalakese** [comment]
Alien Tech. researched but there is no compass @Rseding91

**Comment by Rseding91** [comment]
Enter this in the console: /c game.local_player.force.recipes["alien-compass"].enabled = true
